# Generated by Django 4.0.4 on 2022-05-12 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_customer_phone_field_alter_customer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_field',
            field=models.CharField(max_length=12),
        ),
    ]
