# Generated by Django 4.0.4 on 2022-05-12 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_customer_phone_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_field',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
