# Generated by Django 4.0.4 on 2022-05-13 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_category_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category_name',
            new_name='name',
        ),
    ]
