# Generated by Django 4.0.4 on 2022-05-20 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_checkoutaddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkoutaddress',
            old_name='apartment_adress',
            new_name='apartment_address',
        ),
        migrations.RenameField(
            model_name='checkoutaddress',
            old_name='street_adress',
            new_name='street_address',
        ),
    ]
