# Generated by Django 4.0.4 on 2022-05-20 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_checkoutaddress_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutaddress',
            name='apartment_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='checkoutaddress',
            name='street_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='checkoutaddress',
            name='zip_code',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
